import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import SidebarRootClient from "../components/SidebarRootClient";

import { AuthProvider } from "@/app/utils/AuthContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" /> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <SidebarRootClient>
            {children}
          </SidebarRootClient>
        </AuthProvider>
      </body>
    </html>
  );
}
